In [2]:
import numpy as np # импорт библиотеки

In [15]:
list_example = [1, 2, 4, 5, 5, 6]
arr = np.array(list_example) # создание массива из списка
arr

array([1, 2, 4, 5, 5, 6])

In [16]:
zer = np.zeros((2, 2)) # создание массива размером 2х2, состоящего из нулей
zer

array([[0., 0.],
       [0., 0.]])

In [17]:
one = np.ones((2, 2, 3)) # создание массива 2х2х3, состоящего из единиц
one

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [18]:
aran = np.arange(2, 7) # создание массива, состоящего из диапазона целых чисел от 2 до 6 включительно
aran

array([2, 3, 4, 5, 6])

In [19]:
lin = np.linspace(0, 1, 101) # создание массива, состоящего из 101 элемента, равномерно распределенных на промежутке от 0 до 1 включительно
lin

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

In [20]:
one.shape # форма трехмерного тензора, состоящего из единиц

(2, 2, 3)

In [21]:
one.dtype # тип данных массива, состоящего из единиц

dtype('float64')

In [24]:
lin[50] # элемент массива под 50-ым индексом

np.float64(0.5)

In [26]:
zer[1, 1] # элемент массива по индесом (1, 1)

np.float64(0.0)

In [28]:
lin[1::2] # срез массива, состоящий из каждго второго элемента массива, начиная с элемента с индексом 1

array([0.01, 0.03, 0.05, 0.07, 0.09, 0.11, 0.13, 0.15, 0.17, 0.19, 0.21,
       0.23, 0.25, 0.27, 0.29, 0.31, 0.33, 0.35, 0.37, 0.39, 0.41, 0.43,
       0.45, 0.47, 0.49, 0.51, 0.53, 0.55, 0.57, 0.59, 0.61, 0.63, 0.65,
       0.67, 0.69, 0.71, 0.73, 0.75, 0.77, 0.79, 0.81, 0.83, 0.85, 0.87,
       0.89, 0.91, 0.93, 0.95, 0.97, 0.99])

In [29]:
arr1 = np.arange(6).reshape(2, 3) # создание массива целых чисел и изменение его формы
arr2 = np.array([[8, 5, 4], [2, 4, 5]]) # создание массива из двумерного списка
arr1 + arr2 # поэлементное сложение массивов

array([[ 8,  6,  6],
       [ 5,  8, 10]])

In [30]:
arr1 * arr2  # поэлементное умножение массивов

array([[ 0,  5,  8],
       [ 6, 16, 25]])

In [31]:
np.mean(arr1) # среднее значение массива

np.float64(2.5)

In [32]:
np.max(arr1) # максимальное значение массива

np.int64(5)